name: upwork_scrapper
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.41.2
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.1.2
  - python=3.9.16
  - readline=8.2
  - setuptools=67.7.2
  - tk=8.6.12
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-generator==1.10
      - async-timeout==4.0.2
      - attrs==23.1.0
      - autopep8==2.0.2
      - beautifulsoup4==4.12.2
      - bs4==0.0.1
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - exceptiongroup==1.1.1
      - fake-headers==1.0.2
      - frozenlist==1.3.3
      - h11==0.14.0
      - html5lib==1.1
      - idna==3.4
      - lxml==4.9.2
      - multidict==6.0.4
      - numpy==1.24.3
      - oauthlib==3.2.2
      - outcome==1.2.0
      - packaging==23.1
      - pandas==2.0.1
      - pycodestyle==2.10.0
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-upwork-oauth2==3.0.4
      - pytz==2023.3
      - requests==2.30.0
      - requests-oauthlib==1.3.1
      - selenium==4.9.1
      - six==1.16.0
      - slack-bolt==1.18.0
      - slack-sdk==3.21.3
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - tomli==2.0.1
      - tqdm==4.65.0
      - trio==0.22.0
      - trio-websocket==0.10.2
      - tzdata==2023.3
      - urllib3==2.0.2
      - webdriver-manager==3.8.6
      - webencodings==0.5.1
      - wsproto==1.2.0
      - yarl==1.9.2
